### ISSUE TITLE
Remote can't find popcorn time client.

### ISSUE THREAD

**Issue by bokiroki** [se-bastiaan/ButterRemote-Android#124]
It can't find desktop popcorn time, i refering to popcorntime.sh version (official)
I did pairing manually and with qr code, and it didnt work, all i get is spining circle..please fix it, its very nice remote

**Comment by Slamgler** [comment]
i have the same problem with the version 0.3.9 downloaded in www.popcorntime.sh, the app don't work for me.

**Comment by se-bastiaan** [comment]
I've been able to reproduce this and will fix it as soon as I have time.
